### PR TITLE
Fix Ember 2.15+

### PR DESCRIPTION
**Pull request by HeroicEric**
This is mostly stolen from https://github.com/thefrontside/ember-let/pull/43 (tanks @rwjblue :))

I made a few changes to get this passing.

- Moved version checker initialization out of init because it was getting clobbered somehow?? and undefined within `setupPreprocessorRegistry`
- Added a workaround to ensure `/vendor` is transpiled (see https://github.com/ember-cli/ember-cli/issues/7505)
- Updated ember 2.15+ version to include support for multiple params (`{{#let "foo" "bar" as |foo bar|}}`)

### CODE REVIEW

**Comment by Robdel12** [comment]
It's Christmas! 🎉

**Comment by yarigpopov** [comment]
We need this update to update `ember-sparkles`

**Comment by Robdel12** [comment]
Thanks @HeroicEric!! This was a much needed PR. I merged it in and cut a git tag, but I don't have permissions to release on NPM. Someone from @thefrontside/staff will have to do that.

**Comment by yarigpopov** [comment]
Thanks a lot!
Looking forward for npm release

**Comment by Robdel12** [comment]
Going to ping @cowboyd / @cafreeman since they've done publishing on this package before.

**Comment by yarigpopov** [comment]
Hello @cowboyd / @cafreeman (or somebody else from @thefrontside/staff ) We would really appreciate if you publish 0.7.0 version to npm

**Comment by cherewaty** [comment]
0.7.0 published to NPM (sorry for the delay, we had to sort out org permissions).

**Pull request merged**
