### PR TITLE
Handle both ember from npm and bower

### LINKED ISSUE #41: TypeError: Invalid Version: undefined
I'm not sure if this is an issue with `ember-let` or `ember-cli-version-checker`.

Here's the stack trace.

```
Invalid Version: undefined
TypeError: Invalid Version: undefined
    at new SemVer (/Users/mingliu/Workspace/prime/node_modules/ember-cli-version-checker/node_modules/semver/semver.js:281:11)
    at compare (/Users/mingliu/Workspace/prime/node_modules/ember-cli-version-checker/node_modules/semver/semver.js:571:10)
    at Function.lt (/Users/mingliu/Workspace/prime/node_modules/ember-cli-version-checker/node_modules/semver/semver.js:605:10)
    at DependencyVersionChecker.(anonymous function) [as lt] (/Users/mingliu/Workspace/prime/node_modules/ember-cli-version-checker/index.js:72:26)
    at Class.setupPreprocessorRegistry (/Users/mingliu/Workspace/prime/node_modules/ember-let/index.js:12:39)
```

I think the issue stem from ember moved bower package to npm. So when `checker.for('ember', 'bower').lt('2.0.0')` tries to check for it, it throws because it expects the bower package.

### PR DESCRIPTION
**Pull request by ming-codes**
Fixes #41

### CODE REVIEW

**Comment by cowboyd** [comment]
@ming-codes Thank you! It looks like this is failing on the ember-beta channel however.

**Comment by ming-codes** [comment]
Looks like it's from glimmer change again.

**Comment by rwjblue** [comment]
Confirm. We will need to track that as a separate issue.

**Comment by rwjblue** [comment]
Also, I believe that https://github.com/thefrontside/ember-let/pull/32 is the better path forward here.

**Comment by Robdel12** [comment]
This was taken care of in #45 I believe

**Pull request closed without merging**
